apiVersion: v1
kind: Service
metadata:
  name: apicurio-registry
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: apicurio-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio-registry
  template:
    metadata:
      labels:
        app: apicurio-registry
    spec:
      containers:
        - name: apicurio-registry
          image: apicurio/apicurio-registry-mem:2.4.3.Final
          ports:
            - containerPort: 8080
          env:
            - name: REGISTRY_ENABLE_MULTITENANCY
              value: "false"
            - name: REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED
              value: "true"
            - name: REGISTRY_DATASOURCE_URL
              value: "kafka://kafka-broker:29092"
            - name: REGISTRY_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-broker:29092" 