apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  ports:
    - port: 8123
      targetPort: 8123
      name: http
    - port: 9004
      targetPort: 9004
      name: native
  selector:
    app: clickhouse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:24.3.3.102
          ports:
            - containerPort: 8123
            - containerPort: 9004
          env:
            - name: CLICKHOUSE_KEEPER_SERVER
              value: "clickhouse-keeper:9181"
          volumeMounts:
            - name: config
              mountPath: /etc/clickhouse-server/config.d/
            - name: users
              mountPath: /etc/clickhouse-server/users.d/
      volumes:
        - name: config
          configMap:
            name: clickhouse-config
        - name: users
          configMap:
            name: clickhouse-users