apiVersion: batch/v1
kind: Job
metadata:
  name: create-connector
spec:
  template:
    spec:
      containers:
      - name: create-connector
        image: curlimages/curl:8.4.0
        command:
        - /bin/sh
        - -c
        - |
          # Wait for Kafka Connect to be ready
          until curl -s http://debezium:8083/connectors; do
            echo "Waiting for Kafka Connect..."
            sleep 5
          done
          
          # Create the connector
          curl -X POST \
            -H "Content-Type: application/json" \
            --data "@/connector-config/postgres-connector.json" \
            http://debezium:8083/connectors
        volumeMounts:
        - name: connector-config
          mountPath: /connector-config
      volumes:
      - name: connector-config
        configMap:
          name: postgres-source-connector
      restartPolicy: OnFailure 