apiVersion: v1
kind: Service
metadata:
  name: debezium
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: debezium
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium
  template:
    metadata:
      labels:
        app: debezium
    spec:
      containers:
        - name: debezium
          image: quay.io/debezium/connect:latest
          ports:
            - containerPort: 8083
          env:
            - name: BOOTSTRAP_SERVERS
              value: "kafka-broker:29092"
            - name: GROUP_ID
              value: "1"
            - name: CONFIG_STORAGE_TOPIC
              value: "connect_configs"
            - name: STATUS_STORAGE_TOPIC
              value: "connect_statuses"
            - name: OFFSET_STORAGE_TOPIC
              value: "connect_offsets"
            - name: ENABLE_DEBEZIUM_SCRIPTING
              value: "true"
          livenessProbe:
            httpGet:
              path: /connectors
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 10 