apiVersion: v1
kind: Service
metadata:
  name: cp-schema-registry
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: cp-schema-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cp-schema-registry
  template:
    metadata:
      labels:
        app: cp-schema-registry
    spec:
      containers:
        - name: cp-schema-registry
          image: confluentinc/cp-schema-registry:7.6.1
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "cp-schema-registry"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "kafka-broker:29092"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081" 